INSERT INTO tb_themes (name) VALUES ('Pine Tree');
INSERT INTO tb_themes (name) VALUES ('Golden Retriever');
INSERT INTO tb_themes (name) VALUES ('Mountain Cabin');
INSERT INTO tb_themes (name) VALUES ('Red Rose');
INSERT INTO tb_themes (name) VALUES ('City Park');
INSERT INTO tb_themes (name) VALUES ('Cactus');
INSERT INTO tb_themes (name) VALUES ('Tiger');
INSERT INTO tb_themes (name) VALUES ('Desert Oasis');
INSERT INTO tb_themes (name) VALUES ('Lighthouse');
INSERT INTO tb_themes (name) VALUES ('Apple Tree');
INSERT INTO tb_themes (name) VALUES ('Penguin');
INSERT INTO tb_themes (name) VALUES ('Garden Shed');
INSERT INTO tb_themes (name) VALUES ('Elephant');
INSERT INTO tb_themes (name) VALUES ('Cherry Blossom');
INSERT INTO tb_themes (name) VALUES ('Tropical Beach');
INSERT INTO tb_themes (name) VALUES ('Maple Leaf');
INSERT INTO tb_themes (name) VALUES ('Mountain Goat');
INSERT INTO tb_themes (name) VALUES ('Forest Path');
INSERT INTO tb_themes (name) VALUES ('Snowy Owl');
INSERT INTO tb_themes (name) VALUES ('Fishing Boat');
INSERT INTO tb_themes (name) VALUES ('Fireplace');
INSERT INTO tb_themes (name) VALUES ('Sunflower');
INSERT INTO tb_themes (name) VALUES ('Polar Bear');
INSERT INTO tb_themes (name) VALUES ('Desert Cactus');
INSERT INTO tb_themes (name) VALUES ('Eagle');
INSERT INTO tb_themes (name) VALUES ('Rainforest');
INSERT INTO tb_themes (name) VALUES ('Panda Bear');
INSERT INTO tb_themes (name) VALUES ('Riverbank');
INSERT INTO tb_themes (name) VALUES ('Rocking Chair');
INSERT INTO tb_themes (name) VALUES ('Hummingbird');
INSERT INTO tb_themes (name) VALUES ('Camping Tent');
INSERT INTO tb_themes (name) VALUES ('Orchid');
INSERT INTO tb_themes (name) VALUES ('Butterfly');
INSERT INTO tb_themes (name) VALUES ('Canoe');
INSERT INTO tb_themes (name) VALUES ('Pinecone');
INSERT INTO tb_themes (name) VALUES ('Sunset Beach');
INSERT INTO tb_themes (name) VALUES ('Oak Tree');
INSERT INTO tb_themes (name) VALUES ('Grizzly Bear');
INSERT INTO tb_themes (name) VALUES ('Rooftop Garden');
INSERT INTO tb_themes (name) VALUES ('Lily Flower');
INSERT INTO tb_themes (name) VALUES ('Bamboo');
INSERT INTO tb_themes (name) VALUES ('Snow Leopard');
INSERT INTO tb_themes (name) VALUES ('Castle Ruins');
INSERT INTO tb_themes (name) VALUES ('Turtle');
INSERT INTO tb_themes (name) VALUES ('Waterfall');
INSERT INTO tb_themes (name) VALUES ('Fern');
INSERT INTO tb_themes (name) VALUES ('Dolphin');
INSERT INTO tb_themes (name) VALUES ('Cottage');
INSERT INTO tb_themes (name) VALUES ('Seashell');
INSERT INTO tb_themes (name) VALUES ('Owl');
INSERT INTO tb_themes (name) VALUES ('Sailing Ship');
INSERT INTO tb_themes (name) VALUES ('Magnolia Tree');
INSERT INTO tb_themes (name) VALUES ('Camel');
INSERT INTO tb_themes (name) VALUES ('Mountain River');
INSERT INTO tb_themes (name) VALUES ('Wildflowers');
INSERT INTO tb_themes (name) VALUES ('Fox');
INSERT INTO tb_themes (name) VALUES ('Barn');
INSERT INTO tb_themes (name) VALUES ('Peacock');
INSERT INTO tb_themes (name) VALUES ('Cherry Tree');
INSERT INTO tb_themes (name) VALUES ('Falcon');
INSERT INTO tb_themes (name) VALUES ('Wooden Bridge');
INSERT INTO tb_themes (name) VALUES ('Rose Garden');
INSERT INTO tb_themes (name) VALUES ('Hedgehog');
INSERT INTO tb_themes (name) VALUES ('Country Road');
INSERT INTO tb_themes (name) VALUES ('Giraffe');
INSERT INTO tb_themes (name) VALUES ('Rainy Street');
INSERT INTO tb_themes (name) VALUES ('Horse Stable');
INSERT INTO tb_themes (name) VALUES ('Tulip Field');
INSERT INTO tb_themes (name) VALUES ('Shark');
INSERT INTO tb_themes (name) VALUES ('Old Windmill');
INSERT INTO tb_themes (name) VALUES ('Daisy');
INSERT INTO tb_themes (name) VALUES ('Cliffside Path');
INSERT INTO tb_themes (name) VALUES ('Seagull');
INSERT INTO tb_themes (name) VALUES ('Wooden Cabin');
INSERT INTO tb_themes (name) VALUES ('Palm Tree');
INSERT INTO tb_themes (name) VALUES ('Wolf');
INSERT INTO tb_themes (name) VALUES ('Coral Reef');
INSERT INTO tb_themes (name) VALUES ('Mountain Peak');
INSERT INTO tb_themes (name) VALUES ('Lavender Field');
INSERT INTO tb_themes (name) VALUES ('Koala Bear');
INSERT INTO tb_themes (name) VALUES ('Canyon');
INSERT INTO tb_themes (name) VALUES ('Wheat Field');
INSERT INTO tb_themes (name) VALUES ('Laptop');
INSERT INTO tb_themes (name) VALUES ('Coffee Mug');
INSERT INTO tb_themes (name) VALUES ('Smartphone');
INSERT INTO tb_themes (name) VALUES ('Backpack');
INSERT INTO tb_themes (name) VALUES ('Wristwatch');
INSERT INTO tb_themes (name) VALUES ('Book');
INSERT INTO tb_themes (name) VALUES ('Headphones');
INSERT INTO tb_themes (name) VALUES ('Desk Lamp');
INSERT INTO tb_themes (name) VALUES ('Chair');
INSERT INTO tb_themes (name) VALUES ('Sunglasses');
INSERT INTO tb_themes (name) VALUES ('Pencil');
INSERT INTO tb_themes (name) VALUES ('Water Bottle');
INSERT INTO tb_themes (name) VALUES ('Umbrella');
INSERT INTO tb_themes (name) VALUES ('Wallet');
INSERT INTO tb_themes (name) VALUES ('Keyboard');
INSERT INTO tb_themes (name) VALUES ('Television Remote');
INSERT INTO tb_themes (name) VALUES ('Shoes');
INSERT INTO tb_themes (name) VALUES ('Scissors');
INSERT INTO tb_themes (name) VALUES ('Notebook');
INSERT INTO tb_themes (name) VALUES ('Camera');
INSERT INTO tb_themes (name) VALUES ('Table');
INSERT INTO tb_themes (name) VALUES ('Mirror');
INSERT INTO tb_themes (name) VALUES ('Backpack');
INSERT INTO tb_themes (name) VALUES ('Gloves');
INSERT INTO tb_themes (name) VALUES ('Headset');
INSERT INTO tb_themes (name) VALUES ('Charger');
INSERT INTO tb_themes (name) VALUES ('Stapler');
INSERT INTO tb_themes (name) VALUES ('Mouse');
INSERT INTO tb_themes (name) VALUES ('Calculator');
INSERT INTO tb_themes (name) VALUES ('Notebook');
INSERT INTO tb_themes (name) VALUES ('Watch');
INSERT INTO tb_themes (name) VALUES ('Keychain');
INSERT INTO tb_themes (name) VALUES ('Mug');
INSERT INTO tb_themes (name) VALUES ('Picture Frame');
INSERT INTO tb_themes (name) VALUES ('Sneakers');
INSERT INTO tb_themes (name) VALUES ('Light Bulb');
INSERT INTO tb_themes (name) VALUES ('Perfume Bottle');
INSERT INTO tb_themes (name) VALUES ('Bicycle');
INSERT INTO tb_themes (name) VALUES ('Pen');
INSERT INTO tb_themes (name) VALUES ('Tablet');
INSERT INTO tb_themes (name) VALUES ('Suitcase');
INSERT INTO tb_themes (name) VALUES ('Sofa');
INSERT INTO tb_themes (name) VALUES ('Blanket');
INSERT INTO tb_themes (name) VALUES ('Fan');
INSERT INTO tb_themes (name) VALUES ('Trash Can');
INSERT INTO tb_themes (name) VALUES ('Iron');
INSERT INTO tb_themes (name) VALUES ('Blender');
INSERT INTO tb_themes (name) VALUES ('Toaster');
INSERT INTO tb_themes (name) VALUES ('Vacuum Cleaner');
INSERT INTO tb_themes (name) VALUES ('Refrigerator');
INSERT INTO tb_themes (name) VALUES ('Washing Machine');
INSERT INTO tb_themes (name) VALUES ('Shampoo Bottle');
INSERT INTO tb_themes (name) VALUES ('Hairbrush');
INSERT INTO tb_themes (name) VALUES ('Laundry Basket');
INSERT INTO tb_themes (name) VALUES ('Dishwasher');
INSERT INTO tb_themes (name) VALUES ('Oven');
INSERT INTO tb_themes (name) VALUES ('Microwave');
INSERT INTO tb_themes (name) VALUES ('Pillow');
INSERT INTO tb_themes (name) VALUES ('Towel');
INSERT INTO tb_themes (name) VALUES ('Toothbrush');
INSERT INTO tb_themes (name) VALUES ('Soap Dispenser');
INSERT INTO tb_themes (name) VALUES ('Shaving Razor');
INSERT INTO tb_themes (name) VALUES ('Screwdriver');
INSERT INTO tb_themes (name) VALUES ('Hammer');
INSERT INTO tb_themes (name) VALUES ('Wrench');
INSERT INTO tb_themes (name) VALUES ('Drill');
INSERT INTO tb_themes (name) VALUES ('Flashlight');
INSERT INTO tb_themes (name) VALUES ('Paintbrush');
INSERT INTO tb_themes (name) VALUES ('Ladder');
INSERT INTO tb_themes (name) VALUES ('Garden Hose');
INSERT INTO tb_themes (name) VALUES ('Flower Pot');
INSERT INTO tb_themes (name) VALUES ('Watering Can');
INSERT INTO tb_themes (name) VALUES ('Frying Pan');
INSERT INTO tb_themes (name) VALUES ('Cooking Pot');
INSERT INTO tb_themes (name) VALUES ('Cutting Board');
INSERT INTO tb_themes (name) VALUES ('Kitchen Knife');
INSERT INTO tb_themes (name) VALUES ('Spatula');
INSERT INTO tb_themes (name) VALUES ('Mixing Bowl');
INSERT INTO tb_themes (name) VALUES ('Measuring Cup');
INSERT INTO tb_themes (name) VALUES ('Pizza Cutter');
INSERT INTO tb_themes (name) VALUES ('Wine Glass');
INSERT INTO tb_themes (name) VALUES ('Bottle Opener');
INSERT INTO tb_themes (name) VALUES ('Coffee Maker');
INSERT INTO tb_themes (name) VALUES ('Mop');
INSERT INTO tb_themes (name) VALUES ('Broom');
INSERT INTO tb_themes (name) VALUES ('Dustpan');
INSERT INTO tb_themes (name) VALUES ('Extension Cord');
INSERT INTO tb_themes (name) VALUES ('Thermometer');
INSERT INTO tb_themes (name) VALUES ('Band-Aid');
INSERT INTO tb_themes (name) VALUES ('Sewing Needle');
INSERT INTO tb_themes (name) VALUES ('Thread');
INSERT INTO tb_themes (name) VALUES ('Measuring Tape');
INSERT INTO tb_themes (name) VALUES ('Hair Dryer');
INSERT INTO tb_themes (name) VALUES ('Safety Pin');
INSERT INTO tb_themes (name) VALUES ('Pocket Knife');
INSERT INTO tb_themes (name) VALUES ('Pizza');
INSERT INTO tb_themes (name) VALUES ('Burger');
INSERT INTO tb_themes (name) VALUES ('Sushi');
INSERT INTO tb_themes (name) VALUES ('Pasta');
INSERT INTO tb_themes (name) VALUES ('Salad');
INSERT INTO tb_themes (name) VALUES ('Sandwich');
INSERT INTO tb_themes (name) VALUES ('Tacos');
INSERT INTO tb_themes (name) VALUES ('Hot Dog');
INSERT INTO tb_themes (name) VALUES ('Steak');
INSERT INTO tb_themes (name) VALUES ('Chicken Wings');
INSERT INTO tb_themes (name) VALUES ('Fried Rice');
INSERT INTO tb_themes (name) VALUES ('Ice Cream');
INSERT INTO tb_themes (name) VALUES ('Pancakes');
INSERT INTO tb_themes (name) VALUES ('Waffles');
INSERT INTO tb_themes (name) VALUES ('Donuts');
INSERT INTO tb_themes (name) VALUES ('Cupcakes');
INSERT INTO tb_themes (name) VALUES ('Brownies');
INSERT INTO tb_themes (name) VALUES ('Cookies');
INSERT INTO tb_themes (name) VALUES ('Cheesecake');
INSERT INTO tb_themes (name) VALUES ('Pie');
INSERT INTO tb_themes (name) VALUES ('Muffins');
INSERT INTO tb_themes (name) VALUES ('Quiche');
INSERT INTO tb_themes (name) VALUES ('Burrito');
INSERT INTO tb_themes (name) VALUES ('Falafel');
INSERT INTO tb_themes (name) VALUES ('Gyro');
INSERT INTO tb_themes (name) VALUES ('Kebab');
INSERT INTO tb_themes (name) VALUES ('Noodles');
INSERT INTO tb_themes (name) VALUES ('Soup');
INSERT INTO tb_themes (name) VALUES ('Chili');
INSERT INTO tb_themes (name) VALUES ('Curry');
INSERT INTO tb_themes (name) VALUES ('Paella');
INSERT INTO tb_themes (name) VALUES ('Ramen');
INSERT INTO tb_themes (name) VALUES ('Spring Rolls');
INSERT INTO tb_themes (name) VALUES ('Dim Sum');
INSERT INTO tb_themes (name) VALUES ('Bagel');
INSERT INTO tb_themes (name) VALUES ('Toast');
INSERT INTO tb_themes (name) VALUES ('Omelette');
INSERT INTO tb_themes (name) VALUES ('Grits');
INSERT INTO tb_themes (name) VALUES ('Grilled Cheese');
INSERT INTO tb_themes (name) VALUES ('Casserole');
INSERT INTO tb_themes (name) VALUES ('Pot Roast');
INSERT INTO tb_themes (name) VALUES ('Brisket');
INSERT INTO tb_themes (name) VALUES ('Tuna Salad');
INSERT INTO tb_themes (name) VALUES ('Macaroni and Cheese');
INSERT INTO tb_themes (name) VALUES ('Chicken Parmesan');
INSERT INTO tb_themes (name) VALUES ('Beef Stroganoff');
INSERT INTO tb_themes (name) VALUES ('Samosas');
INSERT INTO tb_themes (name) VALUES ('Spring Rolls');
INSERT INTO tb_themes (name) VALUES ('Empanadas');
INSERT INTO tb_themes (name) VALUES ('Cheese Fries');
INSERT INTO tb_themes (name) VALUES ('Onion Rings');
INSERT INTO tb_themes (name) VALUES ('Mozzarella Sticks');
INSERT INTO tb_themes (name) VALUES ('Garlic Bread');
INSERT INTO tb_themes (name) VALUES ('Breadsticks');
INSERT INTO tb_themes (name) VALUES ('Pita Bread');
INSERT INTO tb_themes (name) VALUES ('Hummus');
INSERT INTO tb_themes (name) VALUES ('Guacamole');
INSERT INTO tb_themes (name) VALUES ('Salsa');
INSERT INTO tb_themes (name) VALUES ('Chips');
INSERT INTO tb_themes (name) VALUES ('Pretzels');
INSERT INTO tb_themes (name) VALUES ('Popcorn');
INSERT INTO tb_themes (name) VALUES ('Nachos');
INSERT INTO tb_themes (name) VALUES ('Fajitas');
INSERT INTO tb_themes (name) VALUES ('Chicken Tenders');
INSERT INTO tb_themes (name) VALUES ('Chicken Nuggets');
INSERT INTO tb_themes (name) VALUES ('Sloppy Joes');
INSERT INTO tb_themes (name) VALUES ('Cornbread');
INSERT INTO tb_themes (name) VALUES ('Biscuits');
INSERT INTO tb_themes (name) VALUES ('Gravy');
INSERT INTO tb_themes (name) VALUES ('Pudding');
INSERT INTO tb_themes (name) VALUES ('Jello');
INSERT INTO tb_themes (name) VALUES ('Fruit Salad');
INSERT INTO tb_themes (name) VALUES ('Yogurt');
INSERT INTO tb_themes (name) VALUES ('Smoothie');
INSERT INTO tb_themes (name) VALUES ('Milkshake');
INSERT INTO tb_themes (name) VALUES ('Lemonade');
INSERT INTO tb_themes (name) VALUES ('Tea');
INSERT INTO tb_themes (name) VALUES ('Coffee');
INSERT INTO tb_themes (name) VALUES ('Hot Chocolate');
INSERT INTO tb_themes (name) VALUES ('Scone');
INSERT INTO tb_themes (name) VALUES ('Danish');
INSERT INTO tb_themes (name) VALUES ('Croissant');
INSERT INTO tb_themes (name) VALUES ('Tiramisu');
INSERT INTO tb_themes (name) VALUES ('Crepes');
INSERT INTO tb_themes (name) VALUES ('Macarons');
INSERT INTO tb_themes (name) VALUES ('Churros');
INSERT INTO tb_themes (name) VALUES ('Cannoli');
INSERT INTO tb_themes (name) VALUES ('Gelato');
INSERT INTO tb_themes (name) VALUES ('Sorbet');
INSERT INTO tb_themes (name) VALUES ('Fruit Tart');
INSERT INTO tb_themes (name) VALUES ('Cheeseburger');
INSERT INTO tb_themes (name) VALUES ('Chicken Caesar Salad');
INSERT INTO tb_themes (name) VALUES ('Beef Tacos');
INSERT INTO tb_themes (name) VALUES ('Vegetable Stir Fry');
INSERT INTO tb_themes (name) VALUES ('Pork Ribs');
INSERT INTO tb_themes (name) VALUES ('Grilled Salmon');
INSERT INTO tb_themes (name) VALUES ('Baked Ziti');
